/**
 * A small, purpose-built parser for the `gcc.1` man page.
 *
 * `gcc.1` is generated by `pod2man`, which emits a very regular subset of
 * troff. We only need to understand that subset, so instead of shelling out to
 * groff (which would flatten the structure we care about) we walk the source
 * and rebuild it as Markdown, keeping track of which `.SH`/`.SS` section each
 * option entry belongs to.
 */

// --- inline escapes ---------------------------------------------------------

const STRINGS = new Map(Object.entries({
  '\\*(C+': 'C++',
  '\\*(--': '--',
  '\\*(-|': '-',
  '\\*(L"': '"',
  '\\*(R"': '"',
  '\\*(lq': '"',
  '\\*(rq': '"',
  '\\*(Aq': "'",
  '\\*(aq': "'",
  '\\*(dg': '†',
  '\\*(Tm': '™',
  '\\*(R': '®',
  '\\*(D-': 'Ð',
  '\\*(d-': 'ð',
  '\\*(Th': 'Þ',
  '\\*(th': 'þ',
}));

const SPECIALS = new Map(Object.entries({
  '\\(bu': '•',
  '\\(en': '–',
  '\\(em': '—',
  '\\(rq': '”',
  '\\(lq': '“',
  '\\(aq': "'",
  '\\(dq': '"',
  '\\(co': '©',
  '\\(rg': '®',
  '\\(tm': '™',
  '\\(->': '→',
  '\\(<-': '←',
  '\\(mu': '×',
  '\\(ti': '~',
  '\\(ha': '^',
  '\\(ga': '`',
  '\\(sl': '/',
  '\\(rs': '\\',
  '\\(dd': '‡',
  '\\(de': '°',
  '\\(*a': 'α',
  '\\(+-': '±',
}));

/**
 * Splits a troff line into styled runs. `font` is one of R (roman), B (bold),
 * I (italic) or CW (constant width / code).
 */
function tokenize(line) {
  const runs = [];
  const fonts = ['R'];
  let buf = '';
  let i = 0;

  const flush = () => {
    if (buf) runs.push({ text: buf, font: fonts[fonts.length - 1] });
    buf = '';
  };

  while (i < line.length) {
    const ch = line[i];
    if (ch !== '\\') { buf += ch; i += 1; continue; }

    const two = line.slice(i, i + 2);
    const three = line.slice(i, i + 3);

    // Code spans: \*(C`...\*(C'
    if (three === '\\*(' && (line.slice(i, i + 5) === '\\*(C`' || line.slice(i, i + 5) === "\\*(C'")) {
      flush();
      if (line.slice(i, i + 5) === '\\*(C`') fonts.push('CW');
      else if (fonts.length > 1) fonts.pop();
      i += 5;
      continue;
    }

    // Font changes
    if (three === '\\f(') {
      flush();
      const name = line.slice(i + 3, i + 5);
      fonts.push(name === 'CW' || name === 'CB' || name === 'CI' ? 'CW' : 'R');
      i += 5;
      continue;
    }
    if (two === '\\f') {
      const f = line[i + 2];
      if (f === '[') {                       // \f[R] style
        const end = line.indexOf(']', i);
        flush();
        const name = line.slice(i + 3, end);
        if (name === 'R' || name === 'P') { if (fonts.length > 1) fonts.pop(); }
        else fonts.push(name.startsWith('C') ? 'CW' : name[0]);
        i = end + 1;
        continue;
      }
      flush();
      if (f === 'R' || f === 'P') { if (fonts.length > 1) fonts.pop(); }
      else fonts.push(f === 'B' ? 'B' : f === 'I' ? 'I' : 'R');
      i += 3;
      continue;
    }

    // Size changes: \s-1 ... \s0  (pod2man's small caps, no visual meaning here)
    if (two === '\\s') {
      const m = /^\\s[-+]?\d/.exec(line.slice(i));
      if (m) { i += m[0].length; continue; }
    }

    // Named strings and special characters
    let matched = false;
    for (const [seq, repl] of STRINGS) {
      if (line.startsWith(seq, i)) { buf += repl; i += seq.length; matched = true; break; }
    }
    if (matched) continue;
    for (const [seq, repl] of SPECIALS) {
      if (line.startsWith(seq, i)) { buf += repl; i += seq.length; matched = true; break; }
    }
    if (matched) continue;

    if (two === '\\&') { i += 2; continue; }          // zero-width
    if (two === '\\|' || two === '\\^') { i += 2; continue; }
    if (two === '\\ ') { buf += ' '; i += 2; continue; }
    if (two === '\\-') { buf += '-'; i += 2; continue; }
    if (two === '\\e') { buf += '\\'; i += 2; continue; }
    if (two === '\\\\') { buf += '\\'; i += 2; continue; }
    if (two === '\\%') { i += 2; continue; }          // hyphenation hint
    if (two === '\\c') { i += 2; continue; }
    if (two === '\\{' || two === '\\}') { i += 2; continue; }

    buf += line[i + 1] ?? '';
    i += 2;
  }
  flush();
  return runs;
}

const MD_ESCAPE = /([\\`*_[\]<>])/g;

/** Renders a troff line as Markdown. */
export function renderInline(line) {
  let out = '';
  for (const run of tokenize(line)) {
    const text = run.text;
    if (!text) continue;
    if (run.font === 'CW') {
      out += '`' + text.replace(/`/g, '‘') + '`';
    } else if (run.font === 'B') {
      const t = text.replace(MD_ESCAPE, '\\$1');
      out += t.trim() ? t.replace(/^(\s*)(.*?)(\s*)$/s, '$1**$2**$3') : t;
    } else if (run.font === 'I') {
      const t = text.replace(MD_ESCAPE, '\\$1');
      out += t.trim() ? t.replace(/^(\s*)(.*?)(\s*)$/s, '$1_$2_$3') : t;
    } else {
      out += text.replace(MD_ESCAPE, '\\$1');
    }
  }
  return out;
}

/**
 * The bold runs of a troff line, i.e. the literal text of an option with its
 * metavariables (which pod2man sets in italics) removed:
 * `\\fB\\-L\\fR\\fIdir\\fR` -> `-L`
 */
export function renderBold(line) {
  return tokenize(line)
    .filter((r) => r.font === 'B')
    .map((r) => r.text)
    .join('')
    .trim();
}

/** Renders a troff line as plain text (used for headings and item labels). */
export function renderPlain(line) {
  return tokenize(line).map((r) => r.text).join('').replace(/\s+/g, ' ').trim();
}

// --- block structure --------------------------------------------------------

/** Splits `.IP "a" 4` style arguments, honouring double quotes. */
function splitArgs(rest) {
  const args = [];
  let i = 0;
  while (i < rest.length) {
    while (rest[i] === ' ') i += 1;
    if (i >= rest.length) break;
    if (rest[i] === '"') {
      let j = i + 1;
      let val = '';
      while (j < rest.length) {
        if (rest[j] === '"' && rest[j + 1] === '"') { val += '"'; j += 2; continue; }
        if (rest[j] === '"') break;
        val += rest[j];
        j += 1;
      }
      args.push(val);
      i = j + 1;
    } else {
      let j = i;
      while (j < rest.length && rest[j] !== ' ') j += 1;
      args.push(rest.slice(i, j));
      i = j;
    }
  }
  return args;
}

const IGNORED = new Set([
  '.IX', '.PD', '.PP', '.LP', '.P', '.ne', '.nr', '.rr', '.ds', '.de', '.tr',
  '.TH', '.am', '.rm', '.na', '.ad', '.hy', '.nh', '.ft', '.ll', '.in', '.sp',
  '.\\"', '.', '..', '.br', '.ie', '.el', '.if', '.\\}', '.Sh',
]);

/**
 * Parses the whole man page.
 *
 * @returns {{ items: Map<string, Item>, order: string[] }}
 *   `items` is keyed by option name (an entry documenting several spellings is
 *   reachable under each of them).
 */
export function parseManPage(source) {
  const lines = source.split('\n');

  let section = '';
  let subsection = '';
  let group = '';
  let depth = 0;
  let current = null;          // { names, label, section, subsection, blocks }
  const entries = [];
  let pendingNames = [];       // consecutive `.IP`s that share one body

  let verbatim = null;         // string[] while inside .Vb / .Ve
  let para = [];               // accumulating inline lines

  const flushPara = () => {
    if (!para.length) return;
    const text = para.join('\n').replace(/\n{3,}/g, '\n\n').trim();
    if (text && current) current.blocks.push({ type: 'p', text });
    para = [];
  };

  const startEntry = (label, ixName, bold) => {
    flushPara();
    current = {
      label,
      ixName,
      bold,
      section,
      subsection,
      group,
      blocks: [],
    };
    entries.push(current);
  };

  for (let idx = 0; idx < lines.length; idx += 1) {
    let line = lines[idx];

    if (verbatim !== null) {
      if (line.startsWith('.Ve')) {
        const code = verbatim.join('\n').replace(/\s+$/, '');
        if (code.trim() && current) {
          flushPara();
          current.blocks.push({ type: 'code', text: code });
        }
        verbatim = null;
      } else {
        verbatim.push(renderPlain(line.replace(/^\\&/, '')) === ''
          ? ''
          : tokenize(line.replace(/^\\&/, '')).map((r) => r.text).join('').replace(/\s+$/, ''));
      }
      continue;
    }

    // `.ie n X` / `.el Y`: keep the troff branch, it carries the real markup.
    if (/^\.ie\s+n\s/.test(line)) {
      const next = lines[idx + 1] ?? '';
      if (/^\.el\s/.test(next)) { continue; }        // handled on the .el line
      line = line.replace(/^\.ie\s+n\s+/, '');
    } else if (/^\.el\s/.test(line)) {
      line = line.replace(/^\.el\s+/, '');
    } else if (/^\.if\s+n\s*\\\{/.test(line)) {
      while (idx < lines.length && !/^\.\\}/.test(lines[idx])) idx += 1;
      continue;
    } else if (/^\.if\s+t\s+/.test(line)) {
      line = line.replace(/^\.if\s+t\s+/, '');
    } else if (/^\.if\s/.test(line)) {
      continue;
    }

    if (line.startsWith('.\\"')) continue;

    if (line.startsWith('.Vb')) { flushPara(); verbatim = []; continue; }

    if (line.startsWith('.SH ') || line.startsWith('.Sh ')) {
      flushPara();
      current = null;
      pendingNames = [];
      section = renderPlain(splitArgs(line.slice(4))[0] ?? '');
      subsection = '';
      group = '';
      continue;
    }
    if (line.startsWith('.SS ') || line.startsWith('.Ss ')) {
      flushPara();
      current = null;
      pendingNames = [];
      subsection = renderPlain(splitArgs(line.slice(4))[0] ?? '');
      group = '';
      continue;
    }
    // `.IX Subsection "AArch64 Options"` marks the per-architecture groups
    // inside "Machine-Dependent Options".
    const ixSub = /^\.IX Subsection "(.*)"\s*$/.exec(line);
    if (ixSub) {
      flushPara();
      current = null;
      pendingNames = [];
      group = ixSub[1];
      continue;
    }

    if (line.startsWith('.RS')) { flushPara(); depth += 1; continue; }
    if (line.startsWith('.RE')) { flushPara(); depth = Math.max(0, depth - 1); continue; }

    if (line.startsWith('.IP ')) {
      const label = splitArgs(line.slice(4))[0] ?? '';
      // The `.IX Item "..."` right below gives the label without any markup.
      const ix = /^\.IX Item "(.*)"\s*$/.exec(lines[idx + 1] ?? '');
      const ixName = ix ? ix[1] : renderPlain(label);
      if (depth === 0) {
        startEntry(renderInline(label).trim(), ixName, renderBold(label));
        pendingNames.push(current);
      } else {
        flushPara();
        if (current) current.blocks.push({ type: 'dt', text: renderInline(label).trim() });
      }
      continue;
    }

    if (line.startsWith('.Sp') || line === '.PP' || line === '.LP') { flushPara(); continue; }
    if (line.startsWith('.')) {
      const cmd = line.split(/\s/)[0];
      if (IGNORED.has(cmd) || /^\.[A-Za-z\\]/.test(cmd)) continue;
    }

    if (line.trim() === '') { flushPara(); continue; }
    para.push(renderInline(line));
  }
  flushPara();

  return entries;
}

/** Turns the block list of an entry into a Markdown string. */
export function blocksToMarkdown(blocks) {
  const out = [];
  for (const b of blocks) {
    if (b.type === 'p') out.push(b.text);
    else if (b.type === 'code') out.push('```\n' + b.text + '\n```');
    else if (b.type === 'dt') out.push('- ' + b.text);
  }
  return out.join('\n\n').replace(/\n{3,}/g, '\n\n').trim();
}

// --- option name extraction -------------------------------------------------

/**
 * Every spelling under which a man page entry should be reachable.
 *
 * The man page writes options the way a human reads them (`-flto[=n]`,
 * `-mabi=name`, `-Wno-shadow`) while `gcc --help` uses canonical stems
 * (`-flto=`, `-mabi=`, `-Wshadow`), so an entry is indexed under several keys
 * and the dataset builder picks the best match.
 */
export function manKeys(entry) {
  const plain = (entry.ixName || renderPlain(entry.label) || '')
    .replace(/\s*\([^)]*\)\s*$/, '')
    .trim();
  if (!plain.startsWith('-') && !(entry.bold || '').startsWith('-')) return [];

  const first = plain.split(/[\s,]+/)[0];
  const keys = new Set();
  const add = (k) => { if (k && k.startsWith('-') && k.length > 1) keys.add(k); };

  const bold = (entry.bold || '').split(/[\s,]+(?=-)/)[0];
  for (const base of [bold, plain, first].filter(Boolean)) {
    add(base);
    const noBracket = base.replace(/\[[^\]]*\]/g, '');
    add(noBracket);
    for (const v of [base, noBracket]) {
      const eq = v.indexOf('=');
      if (eq > 0) {
        add(v.slice(0, eq + 1));
        add(v.slice(0, eq));
      }
      const comma = v.indexOf(',');
      if (comma > 0) add(v.slice(0, comma + 1));
      if (!v.includes('=')) add(v + '=');
      // `-Wno-foo` documents `-Wfoo`, `-fno-bar` documents `-fbar`
      add(v.replace(/^(-[Wfm])no-/, '$1'));
      const eq2 = v.replace(/^(-[Wfm])no-/, '$1').indexOf('=');
      if (eq2 > 0) add(v.replace(/^(-[Wfm])no-/, '$1').slice(0, eq2 + 1));
    }
  }
  return [...keys];
}

/**
 * The single canonical spelling for a man page entry, used when the option is
 * documented but never listed by `gcc --help` on this host (linker, driver and
 * cross-target options).
 */
export function manPrimary(entry) {
  let name = (entry.bold || '').trim();
  if (!name.startsWith('-')) {
    name = (entry.ixName || '').replace(/\s*\([^)]*\)\s*$/, '').split(/[\s,]+/)[0];
  }
  if (!name.startsWith('-')) return null;
  name = name.replace(/\[[^\]]*\]/g, '').replace(/[\s.;:]+$/, '');
  if (name.length < 2) return null;
  return name;
}
