/**
 * Turns a flag selection into something a build system can consume.
 *
 * Every exporter receives the flags already split into a compile list and a
 * link list, because getting that split wrong is the usual reason a hardened
 * build silently loses half its mitigations (`-fsanitize=`, `-flto` and `-pie`
 * have to appear on *both* command lines).
 */
import type { OptionRow } from './types';

export interface SelectedFlag {
  name: string;
  value: string;
  row?: OptionRow;
  /** The full flag as typed on a command line. */
  flag: string;
}

export type Stage = 'compile' | 'link' | 'both';

/** Flags that must be repeated on the link command line to have any effect. */
const BOTH = [
  /^-fsanitize=/, /^-flto/, /^-fprofile/, /^-pg$/, /^-fuse-ld=/, /^-static/,
  /^-fPIE$/, /^-fpie$/, /^-fPIC$/, /^-fpic$/, /^-fno-lto$/, /^-fopenmp/,
  /^-pthread$/, /^-fstack-protector/, /^-fcf-protection/,
];

const LINK_ONLY = [
  /^-Wl,/, /^-Xlinker/, /^-l/, /^-L/, /^-shared$/, /^-pie$/, /^-no-pie$/,
  /^-rdynamic$/, /^-symbolic$/, /^-nostdlib/, /^-nodefaultlibs$/,
  /^-nostartfiles$/, /^-nolibc$/, /^-r$/, /^-s$/, /^-T/, /^-u /, /^-z /,
  /^--entry=/, /^-e /,
];

export function flagStage(flag: string, row?: OptionRow): Stage {
  if (BOTH.some((re) => re.test(flag))) return 'both';
  if (LINK_ONLY.some((re) => re.test(flag))) return 'link';
  if (row?.c === 'link') return 'link';
  return 'compile';
}

export function buildFlag(name: string, value: string): string {
  return value ? `${name}${value}` : name;
}

export interface SplitFlags {
  compile: string[];
  link: string[];
  all: string[];
}

export function splitFlags(flags: SelectedFlag[]): SplitFlags {
  const compile: string[] = [];
  const link: string[] = [];
  for (const f of flags) {
    const stage = flagStage(f.flag, f.row);
    if (stage !== 'link') compile.push(f.flag);
    if (stage !== 'compile') link.push(f.flag);
  }
  return { compile, link, all: flags.map((f) => f.flag) };
}

export interface ExportFormat {
  id: string;
  label: string;
  filename: string;
  language: string;
  blurb: string;
  render: (s: SplitFlags, meta: ExportMeta) => string;
}

export interface ExportMeta {
  generatedAt: string;
  gccVersion: number;
  profileNames: string[];
}

const header = (meta: ExportMeta, comment: string) => {
  const lines = [
    'Generated by GCC Explorer',
    `Target toolchain: GCC ${meta.gccVersion}`,
    meta.profileNames.length ? `Profiles: ${meta.profileNames.join(', ')}` : null,
    meta.generatedAt,
  ].filter(Boolean) as string[];
  return lines.map((l) => `${comment} ${l}`).join('\n');
};

const wrap = (flags: string[], indent: string) =>
  flags.map((f) => `${indent}${f}`).join('\n');

export const FORMATS: ExportFormat[] = [
  {
    id: 'shell',
    label: 'Shell / CFLAGS',
    filename: 'gcc-flags.sh',
    language: 'bash',
    blurb: 'Plain environment variables — works with anything that reads CFLAGS.',
    render: (s, m) => `${header(m, '#')}

export CFLAGS="${s.compile.join(' ')}"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="${s.link.join(' ')}"
`,
  },
  {
    id: 'make',
    label: 'Make',
    filename: 'flags.mk',
    language: 'makefile',
    blurb: 'Include from a Makefile with `include flags.mk`.',
    render: (s, m) => `${header(m, '#')}

CFLAGS += \\
${wrap(s.compile, '  ')
      .split('\n')
      .map((l, i, a) => (i === a.length - 1 ? l : `${l} \\`))
      .join('\n')}

CXXFLAGS += $(CFLAGS)

LDFLAGS += \\
${wrap(s.link, '  ')
      .split('\n')
      .map((l, i, a) => (i === a.length - 1 ? l : `${l} \\`))
      .join('\n')}
`,
  },
  {
    id: 'cmake',
    label: 'CMake',
    filename: 'GccFlags.cmake',
    language: 'cmake',
    blurb: 'A function you call on each target — no global CMAKE_C_FLAGS abuse.',
    render: (s, m) => `${header(m, '#')}

# Usage:  include(GccFlags)
#         gccx_apply_flags(my_target)

function(gccx_apply_flags target)
  target_compile_options(\${target} PRIVATE
${wrap(s.compile, '    ')}
  )
  target_link_options(\${target} PRIVATE
${wrap(s.link, '    ')}
  )
endfunction()
`,
  },
  {
    id: 'meson',
    label: 'Meson',
    filename: 'gcc_flags.build',
    language: 'meson',
    blurb: 'Arrays you can pass as c_args / link_args, filtered by compiler support.',
    render: (s, m) => `${header(m, '#')}

cc = meson.get_compiler('c')

gccx_compile_args = cc.get_supported_arguments([
${s.compile.map((f) => `  '${f}',`).join('\n')}
])

gccx_link_args = cc.get_supported_link_arguments([
${s.link.map((f) => `  '${f}',`).join('\n')}
])

# executable('app', 'main.c', c_args: gccx_compile_args, link_args: gccx_link_args)
`,
  },
  {
    id: 'bazel',
    label: 'Bazel',
    filename: 'gcc_flags.bzl',
    language: 'python',
    blurb: 'copts / linkopts lists to splice into a cc_binary or cc_library.',
    render: (s, m) => `${header(m, '#')}

GCCX_COPTS = [
${s.compile.map((f) => `    "${f}",`).join('\n')}
]

GCCX_LINKOPTS = [
${s.link.map((f) => `    "${f}",`).join('\n')}
]

# cc_binary(name = "app", srcs = ["main.c"], copts = GCCX_COPTS, linkopts = GCCX_LINKOPTS)
`,
  },
  {
    id: 'autotools',
    label: 'Autotools',
    filename: 'gcc-flags.m4',
    language: 'makefile',
    blurb: 'Drop into configure.ac, then use AM_CFLAGS / AM_LDFLAGS in Makefile.am.',
    render: (s, m) => `${header(m, 'dnl')}

AC_SUBST([GCCX_CFLAGS], ["${s.compile.join(' ')}"])
AC_SUBST([GCCX_LDFLAGS], ["${s.link.join(' ')}"])

dnl Makefile.am:
dnl   AM_CFLAGS  = $(GCCX_CFLAGS)
dnl   AM_LDFLAGS = $(GCCX_LDFLAGS)
`,
  },
  {
    id: 'ninja',
    label: 'Ninja',
    filename: 'gcc_flags.ninja',
    language: 'ini',
    blurb: 'Variables for a hand-written build.ninja.',
    render: (s, m) => `${header(m, '#')}

cflags = ${s.compile.join(' ')}
ldflags = ${s.link.join(' ')}

rule cc
  command = gcc -MMD -MF $out.d $cflags -c $in -o $out
  depfile = $out.d

rule link
  command = gcc $in $ldflags -o $out
`,
  },
  {
    id: 'ant',
    label: 'Ant (cpptasks)',
    filename: 'gcc-flags.xml',
    language: 'xml',
    blurb: 'compilerarg / linkerarg elements for the ant-contrib cpptasks <cc> task.',
    render: (s, m) => `<?xml version="1.0" encoding="UTF-8"?>
<!--
${header(m, ' ')}
-->
<project name="gcc-explorer-flags">
  <fileset id="gccx.sources" dir="src" includes="**/*.c"/>

  <target name="compile">
    <cc name="gcc" objdir="build/obj" outfile="build/app" outtype="executable">
      <fileset refid="gccx.sources"/>
${s.compile.map((f) => `      <compilerarg value="${f.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;')}"/>`).join('\n')}
${s.link.map((f) => `      <linkerarg value="${f.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;')}"/>`).join('\n')}
    </cc>
  </target>
</project>
`,
  },
  {
    id: 'compile-flags',
    label: 'compile_flags.txt',
    filename: 'compile_flags.txt',
    language: 'text',
    blurb: 'One flag per line — what clangd reads when there is no compile_commands.json.',
    render: (s) => `${s.compile.join('\n')}\n`,
  },
  {
    id: 'json',
    label: 'JSON',
    filename: 'gcc-flags.json',
    language: 'json',
    blurb: 'Machine readable, for your own tooling.',
    render: (s, m) => `${JSON.stringify(
      {
        generator: 'GCC Explorer',
        generatedAt: m.generatedAt,
        gcc: m.gccVersion,
        profiles: m.profileNames,
        compile: s.compile,
        link: s.link,
      },
      null,
      2,
    )}\n`,
  },
];

export const FORMAT_BY_ID = new Map(FORMATS.map((f) => [f.id, f]));
