/**
 * Renders the manual text extracted from `gcc.1`.
 *
 * The Markdown is generated by our own pipeline, but it is still passed through
 * DOMPurify: it is machine-produced text from a large upstream document and
 * there is no reason to trust it into `innerHTML` unchecked.
 */
import { marked } from 'marked';
import DOMPurify from 'dompurify';

marked.setOptions({ gfm: true, breaks: false });

const cache = new Map<string, string>();

export function renderMarkdown(md: string): string {
  const hit = cache.get(md);
  if (hit !== undefined) return hit;
  const html = DOMPurify.sanitize(marked.parse(md, { async: false }) as string, {
    ALLOWED_TAGS: ['p', 'strong', 'em', 'code', 'pre', 'ul', 'ol', 'li', 'br', 'a', 'blockquote', 'h4', 'h5'],
    ALLOWED_ATTR: ['href', 'title'],
  });
  if (cache.size > 400) cache.clear();
  cache.set(md, html);
  return html;
}
